use objc2::rc::autoreleasepool;
use objc2_app_kit::{
    NSPasteboard, NSPasteboardType, NSPasteboardTypePNG, NSPasteboardTypeString,
    NSPasteboardTypeTIFF, NSWorkspace,
};
use objc2::runtime::AnyObject;
use objc2_app_kit::NSRunningApplication;
use objc2_core_foundation::CFArray;
use objc2_core_graphics::{kCGNullWindowID, CGWindowListCopyWindowInfo, CGWindowListOption};
use objc2_foundation::{NSArray, NSData, NSDictionary, NSNumber, NSString};

use crate::model::ClipContent;
use crate::watcher::ClipboardBackend;
use crate::{Error, Result};

/// Markers that password managers put on private clipboard content
/// (see nspasteboard.org).
const PRIVATE_TYPES: &[&str] = &[
    "org.nspasteboard.ConcealedType",
    "org.nspasteboard.TransientType",
    "org.nspasteboard.AutoGeneratedType",
];

/// Clipboard backend on top of `NSPasteboard.generalPasteboard`.
#[derive(Default)]
pub struct MacClipboard;

impl ClipboardBackend for MacClipboard {
    fn change_count(&self) -> i64 {
        autoreleasepool(|_| NSPasteboard::generalPasteboard().changeCount() as i64)
    }

    fn read(&self) -> Option<ClipContent> {
        autoreleasepool(|_| {
            let pb = NSPasteboard::generalPasteboard();
            let types = pb.types()?;
            let has = |t: &NSPasteboardType| types.iter().any(|x| x.isEqualToString(t));
            if PRIVATE_TYPES.iter().any(|t| has(&NSString::from_str(t))) {
                return None;
            }
            if let Some(s) = pb.stringForType(unsafe { NSPasteboardTypeString }) {
                return Some(ClipContent::Text(s.to_string()));
            }
            if let Some(d) = pb.dataForType(unsafe { NSPasteboardTypePNG }) {
                return Some(ClipContent::Image(d.to_vec()));
            }
            let tiff = pb.dataForType(unsafe { NSPasteboardTypeTIFF })?;
            tiff_to_png(&tiff.to_vec()).map(ClipContent::Image)
        })
    }

    fn write(&self, content: &ClipContent) -> Result<i64> {
        autoreleasepool(|_| {
            let pb = NSPasteboard::generalPasteboard();
            pb.clearContents();
            let ok = match content {
                ClipContent::Text(s) => {
                    pb.setString_forType(&NSString::from_str(s), unsafe { NSPasteboardTypeString })
                }
                ClipContent::Image(png) => {
                    pb.setData_forType(Some(&NSData::with_bytes(png)), unsafe { NSPasteboardTypePNG })
                }
            };
            if !ok {
                return Err(Error::Clipboard("NSPasteboard refused the data".into()));
            }
            Ok(pb.changeCount() as i64)
        })
    }

    fn frontmost_app(&self) -> Option<String> {
        autoreleasepool(|_| {
            let app = frontmost_window_owner()
                .and_then(NSRunningApplication::runningApplicationWithProcessIdentifier)
                // a process without a window (the background agent) does not get
                // NSWorkspace updates, so this is only a fallback
                .or_else(|| NSWorkspace::sharedWorkspace().frontmostApplication())?;
            Some(app.localizedName()?.to_string())
        })
    }
}

/// PID of the app that owns the frontmost normal window, from the window
/// server's on-screen list (front to back). Owner PID and layer are readable
/// without the screen recording permission; window titles are not used.
fn frontmost_window_owner() -> Option<i32> {
    let list = CGWindowListCopyWindowInfo(
        CGWindowListOption::OptionOnScreenOnly | CGWindowListOption::ExcludeDesktopElements,
        kCGNullWindowID,
    )?;
    // CFArray of CFDictionary is toll-free bridged to NSArray of NSDictionary
    let list: &NSArray<NSDictionary<NSString, AnyObject>> = unsafe { &*(&*list as *const CFArray).cast() };
    let layer_key = NSString::from_str("kCGWindowLayer");
    let pid_key = NSString::from_str("kCGWindowOwnerPID");
    let number = |d: &NSDictionary<NSString, AnyObject>, k: &NSString| {
        d.objectForKey(k)?.downcast::<NSNumber>().ok().map(|n| n.intValue())
    };
    list.iter()
        .find(|w| number(w, &layer_key) == Some(0))
        .and_then(|w| number(&w, &pid_key))
}

fn tiff_to_png(tiff: &[u8]) -> Option<Vec<u8>> {
    let img = image::load_from_memory_with_format(tiff, image::ImageFormat::Tiff).ok()?;
    let mut out = std::io::Cursor::new(Vec::new());
    img.write_to(&mut out, image::ImageFormat::Png).ok()?;
    Some(out.into_inner())
}
